version: '3.9'

name: 'helix'

services:
  server:
    container_name: server
    image: "xavier2p/helix-server"
    ports:
      - "3001:3001"
    restart: always
    networks:
      helix:
        ipv4_address: 10.10.0.2
    depends_on:
      db:
        condition: service_healthy
    environment:
      - HELIX_DB_HOST=db
      - HELIX_DB_USER=root
      - PORT_API=3001
      - HELIX_DB_PORT=5002
      - HELIX_DB_PASSWORD=/run/secrets/db-password
      - HELIX_DB_NAME=helix
      - ACCESS_TOKEN_SECRET=/run/secrets/access-token
      - REFRESH_TOKEN_SECRET=/run/secrets/refresh-token
    volumes:
      - './config:/run/secrets'

  client:
    container_name: client
    image: "xavier2p/helix-client"
    ports:
      - "80:3000"
    restart: always
    networks:
      helix:
        ipv4_address: 10.10.0.4
    depends_on:
      - server
    stdin_open: true
    tty: true
    environment:
      - REACT_APP_API_URL=http://172.16.183.69:3001/api

  db:
    container_name: db
    image: "xavier2p/helix-db"
    ports:
      - "5002:3306"
    restart: always
    networks:
      helix:
        ipv4_address: 10.10.0.3
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    volumes:
      - './config:/run/secrets'
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-uroot',
          '-proot'
        ]
      interval: 5s
      timeout: 5s
      retries: 20

networks:
  helix:
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/16
