version: '3.9'

name: 'helix'

services:
  server:
    image: "xavier2p/helix-server"
    ports:
      - "3001:3001"
    restart: always
    networks:
      helix:
        ipv4_address: 10.10.0.2
    depends_on:
      db:
        condition: service_healthy
    environment:
      HELIX_DB_HOST: "db"
      HELIX_DB_USER: "root"
      PORT_API: "3001"
      HELIX_DB_PORT: "5002"
      HELIX_DB_PASSWORD: "root"
      HELIX_DB_NAME: helix
      ACCESS_TOKEN_SECRET: 6e33d0a512b1e164d3a221057391c9c32bc639494006aed8509c8753b12ac89a4216aafba152fc350dae0777de72dad895d3b92db9caf7718167075531351e16
      REFRESH_TOKEN_SECRET: babfc1221680682bed2a185fd27c887fd43cf4aa27d3e985b0b92e3d8c9bb5d4fd60e22d75e661bc1ab125579f49daf37cb0cbabf586ff19008c836acfdfe81f

  client:
    image: "xavier2p/helix-client"
    ports:
      - "8080:3000"
    restart: always
    networks:
      helix:
        ipv4_address: 10.10.0.4
    depends_on:
      - server
    stdin_open: true
    tty: true
    environment:
      REACT_APP_API_URL: http://localhost:3001/api

  db:
    image: "xavier2p/helix-db"
    ports:
      - "5002:3306"
    restart: always
    networks:
      helix:
        ipv4_address: 10.10.0.3
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "helix"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-ppass"
        ]
      interval: 5s
      timeout: 5s
      retries: 20

networks:
  helix:
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/16
